basePath: /api/v1
definitions:
  domain.Product:
    properties:
      name:
        type: string
      price:
        type: number
    type: object
host: localhost:8081
info:
  contact: {}
  description: API tài liệu cho FoodShop
  title: FoodShop API
  version: "1.0"
paths:
  /foods:
    get:
      consumes:
      - application/json
      description: Trả về danh sách các món ăn
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lấy danh sách món ăn
      tags:
      - foods
    post:
      consumes:
      - application/json
      description: Tạo món ăn mới
      parameters:
      - description: Tạo món ăn thành công
        in: body
        name: food
        required: true
        schema:
          $ref: '#/definitions/domain.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Tạo mới món ăn
      tags:
      - foods
  /foods/{id}:
    get:
      consumes:
      - application/json
      description: Trả về thông tin món ăn theo id
      parameters:
      - description: ID của món ăn
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Lấy thông tin món ăn theo id
      tags:
      - foods
swagger: "2.0"
