app:
  name: 'product-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 8081

logger:
  log_level: 'debug'
  rollbar_env: 'product-service'

postgres:
  host: '192.168.1.28'
  port: 5432
  username: 'postgres'
  password: 'admin'
  database: 'postgres'