// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/labstack/echo/v4"
	"go-foodshop/cmd/product/config"
	"go-foodshop/src/pkg/database"
	"go-foodshop/src/product/usecase"
)

import (
	_ "go-foodshop/cmd/product/docs"
)

// Injectors from wire.go:

func InitApp(config2 *config.Config) (*App, error) {
	postgresConfig := CatPostgresConfig(config2)
	dbContext := database.NewDbContext(postgresConfig)
	repository := usecase.NewPgFoodRepository(dbContext)
	usecaseUsecase := usecase.New(repository)
	echoEcho := echo.New()
	controller := NewController(usecaseUsecase)
	app := NewApp(repository, dbContext, usecaseUsecase, config2, echoEcho, controller)
	return app, nil
}

// wire.go:

func CatPostgresConfig(config2 *config.Config) *database.PostgresConfig {
	return &config2.PostgresConfig
}
